version: '3.5'
services:
  
  ms-example:
    container_name: ms-example
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    image: ms-example
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
      - clickhouse
    environment:
      NODE_ENV: "10"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "3001:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "ms-example"
      RABBITMQ_DEFAULT_PASS: "ms-example"

  clickhouse:
    # 8123 port for HTTP interface
    # 9000 port for native client
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    restart: on-failure
    #volumes:
    #  - ./storage/clickhouse:/var/lib/clickhouse

